### ISSUE TITLE
msgid >= 77 characters produces incorrect output

### ISSUE THREAD

**Issue by cbeley** [andris9/gettext-parser#6] opened 2015-02-02 21:57 UTC
```javascript
var gettextParser = require('gettext-parser');
var data = {
    "translations": {
        "": {
            "dfkjdfkljdfkljdskljdfklsjsdfkljdfsklsdjfklsdfjkldsfjdsflkjsdfkldsfjdskljdsfff": {
                "msgid": "dfkjdfkljdfkljdskljdfklsjsdfkljdfsklsdjfklsdfjkldsfjdsflkjsdfkldsfjdskljdsfff",
                "msgstr": []
            }
        }
    }
};

console.log(gettextParser.po.compile(data).toString());
```

Results in

```
msgid ""
msgstr "Content-Type: text/plain;\n"

msgid ""
"dfkjdfkljdfkljdskljdfklsjsdfkljdfsklsdjfklsdfjkldsfjdsflkjsdfkldsfjdskljdsdf"
"kjdfkljdfkljdskljdfklsjsdfkljdfsklsdjfklsdfjkldsfjdsflkjsdfkldsfjdskljdsdfkj"
"dfkljdfkljdskljdfklsjsdfkljdfsklsdjfklsdfjkldsfjdsflkjsdfkldsfjdskljds"
msgstr ""
```

The issue will not occure with 76 characters.

**Comment by BYK** [comment] 2015-02-03 07:40
Why do you think this is incorrect? AFAIK this is the expected behavior. Consequent string blocks are automatically merged.

**Comment by andris9** [comment] 2015-02-03 07:44
I can't confirm this either. The output sure does look fishy as the msgid in the code and in the output do not match but when I run the sample code myself I get this output which is correct

```
msgid ""
msgstr "Content-Type: text/plain;\n"

msgid ""
"dfkjdfkljdfkljdskljdfklsjsdfkljdfsklsdjfklsdfjkldsfjdsflkjsdfkldsfjdskljdsff"
"f"
msgstr ""
```

I know that the string is folded kind of strangely but this is because the string is one long word. If it would contain spaces or punctuation marks, the folding would look lot nicer.

**Closed by andris9** 2015-02-03 07:44 UTC

**Comment by cbeley** [comment] 2015-02-03 08:07
Ah, well I'm sorry, I didn't realize that msgid could span multiple lines like that (looks kind of odd).  Sorry for the false alarm!
